Metrics/LineLength:
  Max: 160

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

# 1.8 compatible :(
Style/HashSyntax:
  EnforcedStyle: hash_rockets
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma
Style/DotPosition:
  EnforcedStyle: trailing
